//! Render a [`Session`] to a self-contained, shareable HTML page.
//!
//! The output is a single `<!doctype html>` document with all CSS inlined and **no** external
//! assets or JavaScript: it opens offline by double-click, supports light/dark via
//! `prefers-color-scheme`, and is readable on mobile. Every session-derived string is
//! HTML-escaped (see [`escape`]) so a transcript containing `<script>` etc. can never inject
//! markup into the page.

use crate::ir::{Block, Message, Role, Session, Usage};

/// Render `session` as a single self-contained HTML document (inline CSS, no external assets).
pub fn to_html(session: &Session) -> String {
    let mut out = String::new();
    out.push_str("<!doctype html>\n<html lang=\"en\">\n<head>\n");
    out.push_str("<meta charset=\"utf-8\">\n");
    out.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");

    let label = session.label();
    out.push_str("<title>");
    out.push_str(&escape(&label));
    out.push_str("</title>\n");

    out.push_str("<style>\n");
    out.push_str(CSS);
    out.push_str("</style>\n</head>\n<body>\n");

    render_header(session, &label, &mut out);

    out.push_str("<main>\n");
    for m in &session.messages {
        render_message(m, &mut out);
    }
    out.push_str("</main>\n");

    out.push_str(
        "<footer>generated by <strong>claurdvoyant</strong></footer>\n</body>\n</html>\n",
    );
    out
}

fn render_header(session: &Session, label: &str, out: &mut String) {
    out.push_str("<header>\n");
    out.push_str("<h1>");
    out.push_str(&escape(label));
    out.push_str("</h1>\n");

    // Harness badge, color-coded by harness.
    let h = session.harness;
    out.push_str("<div class=\"badges\">");
    out.push_str(&format!(
        "<span class=\"badge\" style=\"background:{}\">{}</span>",
        harness_color(h.as_str()),
        escape(h.as_str()),
    ));
    out.push_str("</div>\n");

    out.push_str("<dl class=\"meta\">\n");
    meta_row(out, "id", &session.id);
    if let Some(cwd) = &session.cwd {
        meta_row(out, "cwd", &cwd.display().to_string());
    }
    if let Some(model) = &session.model {
        meta_row(out, "model", model);
    }
    if let Some(git) = &session.git {
        if let Some(branch) = &git.branch {
            meta_row(out, "branch", branch);
        }
        if let Some(commit) = &git.commit {
            meta_row(out, "commit", commit);
        }
    }
    if let Some(t) = &session.created_at {
        meta_row(out, "created", &t.to_rfc3339());
    }
    if let Some(t) = &session.updated_at {
        meta_row(out, "updated", &t.to_rfc3339());
    }
    meta_row(out, "messages", &session.messages.len().to_string());
    out.push_str("</dl>\n</header>\n");
}

fn meta_row(out: &mut String, key: &str, value: &str) {
    out.push_str("<dt>");
    out.push_str(&escape(key));
    out.push_str("</dt><dd>");
    out.push_str(&escape(value));
    out.push_str("</dd>\n");
}

fn render_message(m: &Message, out: &mut String) {
    let role = role_class(m.role);
    out.push_str(&format!("<section class=\"msg msg-{role}\">\n"));

    out.push_str("<div class=\"msg-head\"><span class=\"role\">");
    out.push_str(&escape(role));
    out.push_str("</span>");
    if let Some(t) = &m.timestamp {
        out.push_str("<span class=\"ts\">");
        out.push_str(&escape(&t.to_rfc3339()));
        out.push_str("</span>");
    }
    out.push_str("</div>\n");

    out.push_str("<div class=\"msg-body\">\n");
    for b in &m.content {
        render_block(b, out);
    }
    out.push_str("</div>\n");

    if let Some(u) = &m.usage {
        render_usage(u, out);
    }

    out.push_str("</section>\n");
}

fn render_block(b: &Block, out: &mut String) {
    match b {
        Block::Text { text } => {
            out.push_str("<div class=\"text\">");
            render_text(text, out);
            out.push_str("</div>\n");
        }
        Block::Thinking { text, redacted, .. } => {
            out.push_str("<details class=\"thinking\"><summary>🧠 reasoning");
            if *redacted {
                out.push_str(" <em>(redacted)</em>");
            }
            out.push_str("</summary>\n");
            if *redacted && text.trim().is_empty() {
                out.push_str("<p class=\"redacted\">[redacted by provider]</p>");
            } else {
                out.push_str("<div class=\"text\">");
                render_text(text, out);
                out.push_str("</div>");
            }
            out.push_str("\n</details>\n");
        }
        Block::ToolUse { name, input, .. } => {
            out.push_str("<div class=\"tool tool-use\">");
            out.push_str("<div class=\"tool-label\">🔧 tool: <code>");
            out.push_str(&escape(name));
            out.push_str("</code></div>");
            let pretty = serde_json::to_string_pretty(input)
                .unwrap_or_else(|_| input.to_string());
            out.push_str("<pre><code>");
            out.push_str(&escape(&pretty));
            out.push_str("</code></pre>");
            out.push_str("</div>\n");
        }
        Block::ToolResult {
            content,
            is_error,
            tool_name,
            status,
            ..
        } => {
            let cls = if *is_error {
                "tool tool-result error"
            } else {
                "tool tool-result"
            };
            out.push_str(&format!("<div class=\"{cls}\">"));
            out.push_str("<div class=\"tool-label\">↩ result");
            if *is_error {
                out.push_str(" <span class=\"err-tag\">error</span>");
            }
            if let Some(name) = tool_name {
                out.push_str(" <code>");
                out.push_str(&escape(name));
                out.push_str("</code>");
            }
            if let Some(s) = status {
                out.push_str(" <span class=\"status\">");
                out.push_str(&escape(s));
                out.push_str("</span>");
            }
            out.push_str("</div>");
            out.push_str("<pre><code>");
            out.push_str(&escape(content));
            out.push_str("</code></pre>");
            out.push_str("</div>\n");
        }
        Block::File { path, source, .. } => {
            let label = path.as_deref().or(source.as_deref()).unwrap_or("?");
            out.push_str("<div class=\"attach\">📎 file: <code>");
            out.push_str(&escape(label));
            out.push_str("</code></div>\n");
        }
        Block::Image { media_type, .. } => {
            out.push_str("<div class=\"attach\">🖼 [image]");
            if let Some(mt) = media_type {
                out.push_str(" <code>");
                out.push_str(&escape(mt));
                out.push_str("</code>");
            }
            out.push_str("</div>\n");
        }
    }
}

fn render_usage(u: &Usage, out: &mut String) {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = u.input_tokens {
        parts.push(format!("in {v}"));
    }
    if let Some(v) = u.output_tokens {
        parts.push(format!("out {v}"));
    }
    if let Some(v) = u.cache_read_tokens {
        parts.push(format!("cache read {v}"));
    }
    if let Some(v) = u.cache_creation_tokens {
        parts.push(format!("cache write {v}"));
    }
    if parts.is_empty() {
        return;
    }
    out.push_str("<div class=\"usage\">tokens: ");
    out.push_str(&escape(&parts.join(" · ")));
    out.push_str("</div>\n");
}

/// Render plain text with minimal, *safe* markdown niceties:
/// - blank lines split paragraphs (`<p>`),
/// - single newlines become `<br>`,
/// - triple-backtick fenced blocks become `<pre><code>`,
/// - inline `` `code` `` becomes `<code>`.
///
/// All text is escaped first; we never trust session content as markup.
fn render_text(text: &str, out: &mut String) {
    // Split on fenced code blocks. A fence is a line that is exactly ``` (optionally with a lang).
    let mut in_fence = false;
    let mut fence_buf = String::new();
    let mut para_buf = String::new();

    let flush_para = |para: &mut String, out: &mut String| {
        let trimmed = para.trim_matches('\n');
        if trimmed.is_empty() {
            para.clear();
            return;
        }
        out.push_str("<p>");
        render_inline(trimmed, out);
        out.push_str("</p>\n");
        para.clear();
    };

    for line in text.split('\n') {
        let is_fence = line.trim_start().starts_with("```");
        if is_fence {
            if in_fence {
                // close fence
                out.push_str("<pre><code>");
                out.push_str(&escape(&fence_buf));
                out.push_str("</code></pre>\n");
                fence_buf.clear();
                in_fence = false;
            } else {
                // open fence — flush any pending paragraph first
                flush_para(&mut para_buf, out);
                in_fence = true;
            }
            continue;
        }
        if in_fence {
            fence_buf.push_str(line);
            fence_buf.push('\n');
            continue;
        }
        if line.trim().is_empty() {
            flush_para(&mut para_buf, out);
        } else {
            if !para_buf.is_empty() {
                para_buf.push('\n');
            }
            para_buf.push_str(line);
        }
    }
    // unterminated fence: render what we have as a code block.
    if in_fence && !fence_buf.is_empty() {
        out.push_str("<pre><code>");
        out.push_str(&escape(&fence_buf));
        out.push_str("</code></pre>\n");
    }
    flush_para(&mut para_buf, out);
}

/// Render a single paragraph's worth of text: escape everything, turn single newlines into
/// `<br>`, and wrap inline `` `code` `` spans in `<code>`.
fn render_inline(s: &str, out: &mut String) {
    let mut rest = s;
    while let Some(start) = rest.find('`') {
        // text before the backtick
        push_with_breaks(&rest[..start], out);
        let after = &rest[start + 1..];
        if let Some(end) = after.find('`') {
            out.push_str("<code>");
            out.push_str(&escape(&after[..end]));
            out.push_str("</code>");
            rest = &after[end + 1..];
        } else {
            // unmatched backtick: treat literally
            push_with_breaks(&rest[start..], out);
            return;
        }
    }
    push_with_breaks(rest, out);
}

/// Escape `s` and convert single `\n` into `<br>`.
fn push_with_breaks(s: &str, out: &mut String) {
    let mut first = true;
    for line in s.split('\n') {
        if !first {
            out.push_str("<br>\n");
        }
        first = false;
        out.push_str(&escape(line));
    }
}

/// HTML-escape the five significant characters. Hand-rolled to keep cv-core dep-light.
/// This is the single trust boundary: every session-derived string passes through here.
pub fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

fn role_class(r: Role) -> &'static str {
    match r {
        Role::System => "system",
        Role::User => "user",
        Role::Assistant => "assistant",
        Role::Tool => "tool",
    }
}

/// A stable, distinct color for each harness badge.
fn harness_color(name: &str) -> &'static str {
    match name {
        "claude" => "#d97757",
        "claude-app" => "#c15f3c",
        "codex" => "#10a37f",
        "chatgpt-app" => "#0e8a6c",
        "grok" => "#1d1d1f",
        "opencode" => "#5b6ee1",
        "gemini" => "#4285f4",
        "hermes" => "#8e44ad",
        "openclaw" => "#b8860b",
        "cursor" => "#111111",
        "kimi" => "#0050ff",
        "qwen" => "#6a3ec0",
        "lmstudio" => "#2563eb",
        "cline" => "#0aa",
        "roo" => "#e0533d",
        "continue" => "#444",
        "goose" => "#7a5c3e",
        _ => "#555",
    }
}

const CSS: &str = r#":root {
  color-scheme: light dark;
  --bg: #ffffff;
  --fg: #1b1b1f;
  --muted: #5c5c66;
  --card: #f6f7f9;
  --card-border: #e2e4e9;
  --user: #2563eb;
  --assistant: #16a34a;
  --system: #9333ea;
  --tool: #b45309;
  --code-bg: #f0f1f4;
  --error-bg: #fdecec;
  --error-fg: #b91c1c;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #16171b;
    --fg: #e6e6ea;
    --muted: #9a9aa5;
    --card: #1e2026;
    --card-border: #2c2f37;
    --user: #60a5fa;
    --assistant: #4ade80;
    --system: #c084fc;
    --tool: #f59e0b;
    --code-bg: #11131a;
    --error-bg: #3a1d1d;
    --error-fg: #fca5a5;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--fg);
  font: 16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  padding: 1.5rem;
}
header, main, footer { max-width: 860px; margin: 0 auto; }
header { padding-bottom: 1rem; border-bottom: 1px solid var(--card-border); margin-bottom: 1.5rem; }
h1 { font-size: 1.5rem; margin: 0 0 .5rem; word-break: break-word; }
.badges { margin-bottom: .75rem; }
.badge {
  display: inline-block; color: #fff; font-size: .72rem; font-weight: 600;
  text-transform: uppercase; letter-spacing: .04em;
  padding: .15rem .5rem; border-radius: 999px;
}
dl.meta {
  display: grid; grid-template-columns: max-content 1fr; gap: .15rem .75rem;
  margin: 0; font-size: .85rem; color: var(--muted);
}
dl.meta dt { font-weight: 600; }
dl.meta dd { margin: 0; word-break: break-word; }
.msg {
  border: 1px solid var(--card-border); border-left-width: 4px;
  border-radius: 8px; margin: 0 0 1rem; background: var(--card);
  overflow: hidden;
}
.msg-user { border-left-color: var(--user); }
.msg-assistant { border-left-color: var(--assistant); }
.msg-system { border-left-color: var(--system); }
.msg-tool { border-left-color: var(--tool); }
.msg-head {
  display: flex; justify-content: space-between; align-items: baseline;
  padding: .5rem .9rem; background: rgba(127,127,127,.06);
  border-bottom: 1px solid var(--card-border);
}
.role { font-weight: 700; text-transform: uppercase; font-size: .75rem; letter-spacing: .05em; }
.msg-user .role { color: var(--user); }
.msg-assistant .role { color: var(--assistant); }
.msg-system .role { color: var(--system); }
.msg-tool .role { color: var(--tool); }
.ts { font-size: .72rem; color: var(--muted); }
.msg-body { padding: .25rem .9rem .6rem; }
.text p { margin: .6rem 0; word-wrap: break-word; }
pre {
  background: var(--code-bg); border: 1px solid var(--card-border);
  border-radius: 6px; padding: .7rem .8rem; overflow-x: auto;
  font: .82rem/1.5 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  margin: .5rem 0;
}
code {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: .9em;
}
.text code, .tool-label code { background: var(--code-bg); padding: .05rem .3rem; border-radius: 4px; }
pre code { background: none; padding: 0; }
details.thinking {
  margin: .5rem 0; background: rgba(127,127,127,.07);
  border: 1px dashed var(--card-border); border-radius: 6px; padding: .3rem .7rem;
}
details.thinking summary { cursor: pointer; color: var(--muted); font-size: .85rem; }
.redacted { color: var(--muted); font-style: italic; }
.tool { margin: .6rem 0; }
.tool-label { font-size: .82rem; font-weight: 600; color: var(--tool); margin-bottom: .15rem; }
.tool-result .tool-label { color: var(--assistant); }
.tool-result.error .tool-label { color: var(--error-fg); }
.tool-result.error pre { background: var(--error-bg); border-color: var(--error-fg); }
.err-tag {
  background: var(--error-fg); color: #fff; border-radius: 4px;
  padding: 0 .35rem; font-size: .72rem;
}
.status { color: var(--muted); font-weight: 400; font-size: .78rem; }
.attach { font-size: .88rem; color: var(--muted); margin: .4rem 0; }
.usage {
  font-size: .72rem; color: var(--muted); padding: .35rem .9rem;
  border-top: 1px solid var(--card-border); background: rgba(127,127,127,.04);
}
footer {
  margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--card-border);
  text-align: center; font-size: .8rem; color: var(--muted);
}
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{Block, GitInfo, Harness, Message, Role, Session, Usage};

    fn sample_session() -> Session {
        let mut user = Message::new(Role::User);
        user.content.push(Block::Text {
            text: "Hello & welcome. Try <script>alert(1)</script> please.\n\nSecond para with `inline` code.".into(),
        });

        let mut assistant = Message::new(Role::Assistant);
        assistant.content.push(Block::Thinking {
            text: "I should be careful with <html>.".into(),
            signature: None,
            encrypted: None,
            redacted: false,
        });
        assistant.content.push(Block::Text {
            text: "Sure! Here is code:\n\n```rust\nfn main() { println!(\"<hi>\"); }\n```".into(),
        });
        assistant.content.push(Block::ToolUse {
            id: "t1".into(),
            name: "Bash".into(),
            input: serde_json::json!({ "command": "echo <x> & done" }),
        });
        assistant.usage = Some(Usage {
            input_tokens: Some(42),
            output_tokens: Some(7),
            cache_read_tokens: None,
            cache_creation_tokens: None,
        });

        let mut tool = Message::new(Role::Tool);
        tool.content.push(Block::ToolResult {
            tool_use_id: "t1".into(),
            content: "stdout: <x> & done".into(),
            is_error: true,
            tool_name: Some("Bash".into()),
            status: Some("error".into()),
            details: None,
        });
        tool.content.push(Block::File {
            mime: None,
            path: Some("/tmp/<weird>&.txt".into()),
            source: None,
        });
        tool.content.push(Block::Image {
            media_type: Some("image/png".into()),
            data_ref: None,
        });

        let mut system = Message::new(Role::System);
        system.content.push(Block::Text {
            text: "You are a helpful assistant.".into(),
        });

        Session {
            id: "abc123".into(),
            harness: Harness::Claude,
            cwd: Some("/home/<user>/proj".into()),
            title: Some("Test & <Session>".into()),
            created_at: None,
            updated_at: None,
            model: Some("claude-opus".into()),
            git: Some(GitInfo {
                branch: Some("dev".into()),
                commit: Some("deadbeef".into()),
                remote: None,
            }),
            messages: vec![system, user, assistant, tool],
            source_path: None,
            extra: serde_json::Map::new(),
        }
    }

    #[test]
    fn escape_handles_all_specials() {
        assert_eq!(escape("a&b"), "a&amp;b");
        assert_eq!(escape("<x>"), "&lt;x&gt;");
        assert_eq!(escape("\"q\""), "&quot;q&quot;");
        assert_eq!(escape("'s'"), "&#39;s&#39;");
        assert_eq!(escape("plain"), "plain");
    }

    #[test]
    fn renders_valid_standalone_document() {
        let html = to_html(&sample_session());
        assert!(html.starts_with("<!doctype html"));
        assert!(html.contains("<html"));
        assert!(html.contains("</html>"));
        // inline CSS, no external assets/scripts
        assert!(html.contains("<style>"));
        assert!(!html.contains("<script"));
        assert!(!html.to_lowercase().contains("src=\"http"));
        assert!(html.len() > 500);
    }

    #[test]
    fn title_is_present_and_escaped() {
        let html = to_html(&sample_session());
        // The title contains & and <Session>; must appear escaped, never raw.
        assert!(html.contains("Test &amp; &lt;Session&gt;"));
        assert!(!html.contains("Test & <Session>"));
    }

    #[test]
    fn xss_payload_is_escaped() {
        let html = to_html(&sample_session());
        // The dangerous payload must be neutralized.
        assert!(html.contains("&lt;script&gt;alert(1)&lt;/script&gt;"));
        assert!(!html.contains("<script>alert"));
        // bare ampersand from user text became an entity
        assert!(html.contains("Hello &amp; welcome"));
    }

    #[test]
    fn all_roles_render() {
        let html = to_html(&sample_session());
        assert!(html.contains("msg-system"));
        assert!(html.contains("msg-user"));
        assert!(html.contains("msg-assistant"));
        assert!(html.contains("msg-tool"));
    }

    #[test]
    fn block_kinds_render() {
        let html = to_html(&sample_session());
        // thinking -> collapsible details
        assert!(html.contains("<details class=\"thinking\""));
        assert!(html.contains("🧠 reasoning"));
        // tool_use -> labeled block with tool name + json
        assert!(html.contains("tool-use"));
        assert!(html.contains("🔧 tool:"));
        assert!(html.contains("Bash"));
        // tool input json is escaped
        assert!(html.contains("echo &lt;x&gt; &amp; done"));
        // tool_result -> error marked + status
        assert!(html.contains("tool-result error"));
        assert!(html.contains("error"));
        // file + image placeholders
        assert!(html.contains("📎 file:"));
        assert!(html.contains("/tmp/&lt;weird&gt;&amp;.txt"));
        assert!(html.contains("[image]"));
        // fenced code block rendered as pre/code
        assert!(html.contains("<pre><code>"));
        assert!(html.contains("println!(&quot;&lt;hi&gt;&quot;)"));
        // inline code
        assert!(html.contains("<code>inline</code>"));
    }

    #[test]
    fn header_and_usage_render() {
        let html = to_html(&sample_session());
        // harness badge
        assert!(html.contains("class=\"badge\""));
        assert!(html.contains("claude"));
        // meta rows
        assert!(html.contains("abc123"));
        assert!(html.contains("claude-opus"));
        assert!(html.contains("dev")); // git branch
        // usage tokens
        assert!(html.contains("tokens:"));
        assert!(html.contains("in 42"));
        assert!(html.contains("out 7"));
        // footer
        assert!(html.contains("generated by"));
        assert!(html.contains("claurdvoyant"));
    }
}
